/** 配置页面的 CSS 样式（minified） */
export const PAGE_CSS = [
    '*{box-sizing:border-box;margin:0;padding:0}',
    ':root{color-scheme:var(--vscode-color-scheme,dark)}',
    'body{font-family:var(--vscode-font-family);font-size:var(--vscode-font-size);',
    'color:var(--vscode-foreground);background:var(--vscode-editor-background);',
    'line-height:1.6;padding:24px 32px;max-width:800px}',
    '.page-title{font-size:20px;font-weight:600;margin-bottom:4px}',
    '.page-desc{font-size:13px;color:var(--vscode-descriptionForeground);margin-bottom:24px}',
    '.cs{margin-bottom:28px}',
    '.cst{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;',
    'margin-bottom:12px;padding-bottom:6px;color:var(--vscode-descriptionForeground);',
    'border-bottom:1px solid var(--vscode-panel-border,rgba(255,255,255,.06))}',
    '.ci{display:flex;align-items:flex-start;gap:16px;padding:12px 0;',
    'border-bottom:1px solid rgba(255,255,255,.03)}',
    '.ci:last-child{border-bottom:none}',
    '.cii{flex:1;min-width:0}',
    '.cil{font-size:13px;font-weight:500;margin-bottom:2px}',
    '.cid{font-size:12px;color:var(--vscode-descriptionForeground)}',
    '.cic{flex-shrink:0;min-width:300px;text-align:right}',
    '.cic input,.cic select{width:100%;background:var(--vscode-input-background);',
    'color:var(--vscode-input-foreground);',
    'border:1px solid var(--vscode-input-border,transparent);',
    'padding:6px 10px;border-radius:4px;font-size:13px;',
    'font-family:var(--vscode-font-family);outline:none}',
    '.cic input:focus,.cic select:focus{border-color:var(--vscode-focusBorder)}',
    '.input-row{display:flex;gap:6px}.input-row input{flex:1;min-width:0}',
].join('') + [
    '.btn{background:var(--vscode-button-secondaryBackground);',
    'color:var(--vscode-button-secondaryForeground);border:none;',
    'padding:6px 14px;border-radius:4px;font-size:12px;cursor:pointer;',
    'font-family:var(--vscode-font-family);white-space:nowrap}',
    '.btn:hover{background:var(--vscode-button-secondaryHoverBackground)}',
    '.btn-primary{background:var(--vscode-button-background);',
    'color:var(--vscode-button-foreground)}',
    '.btn-primary:hover{background:var(--vscode-button-hoverBackground)}',
    '.btn-sm{padding:4px 10px;font-size:11px}',
    '.btn-group{display:inline-flex;border-radius:4px;overflow:hidden;',
    'border:1px solid var(--vscode-input-border,rgba(255,255,255,.1))}',
    '.bgi{padding:5px 14px;font-size:12px;cursor:pointer;background:transparent;',
    'color:var(--vscode-descriptionForeground);border:none;',
    'font-family:var(--vscode-font-family)}',
    '.bgi:not(:last-child){border-right:1px solid var(--vscode-input-border,rgba(255,255,255,.1))}',
    '.bgi.active{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}',
    '.bgi:hover:not(.active){background:rgba(255,255,255,.05)}',
].join('') + [
    '.env-card{background:rgba(255,255,255,.03);border-radius:8px;',
    'padding:16px 20px;margin-bottom:12px}',
    '.env-card.loading{opacity:.72}',
    '@keyframes envspin{to{transform:rotate(360deg)}}',
    '.env-spinner{display:none;width:12px;height:12px;border:2px solid currentColor;',
    'border-right-color:transparent;border-radius:50%;animation:envspin .8s linear infinite;',
    'color:var(--vscode-progressBar-background,#0E70C0)}',
    '.env-card.loading .env-spinner{display:inline-block}',
    '.env-card.loading input,.env-card.loading button,.env-card.loading .csel-trigger{cursor:wait}',
    '.ech{display:flex;align-items:center;gap:10px;margin-bottom:8px}',
    '.ect{font-size:14px;font-weight:600}',
    '.ecb{font-size:11px;padding:2px 8px;border-radius:10px;margin-left:auto}',
    '.bok{background:rgba(34,197,94,.12);color:#22C55E}',
    '.bwn{background:rgba(245,158,11,.12);color:#F59E0B}',
    '.ecp{font-size:12px;color:var(--vscode-descriptionForeground);',
    'word-break:break-all;padding:4px 0;',
    'font-family:var(--vscode-editor-font-family,monospace)}',
    '.eca{margin-top:10px;display:flex;gap:8px}',
].join('') + [
    '.sd{width:8px;height:8px;border-radius:50%;flex-shrink:0}',
    '.dok{background:#22C55E}.dwn{background:#F59E0B}',
    '.toggle-switch{position:relative;display:inline-block;width:36px;height:20px;cursor:pointer}',
    '.toggle-switch input{opacity:0;width:0;height:0;position:absolute}',
    '.toggle-slider{position:absolute;inset:0;background:var(--vscode-input-background);',
    'border:1px solid var(--vscode-input-border,rgba(255,255,255,.1));border-radius:10px;transition:.2s}',
    ".toggle-slider::before{content:'';position:absolute;width:14px;height:14px;",
    'left:2px;bottom:2px;background:var(--vscode-descriptionForeground);border-radius:50%;transition:.2s}',
    '.toggle-switch input:checked+.toggle-slider{background:rgba(34,197,94,.2);border-color:#22C55E}',
    '.toggle-switch input:checked+.toggle-slider::before{transform:translateX(16px);background:#22C55E}',
    '.tag-input{display:flex;flex-wrap:wrap;gap:4px;padding:8px 10px;',
    'background:var(--vscode-input-background);',
    'border:1px solid var(--vscode-input-border,transparent);',
    'border-radius:4px;min-height:56px;max-width:100%;width:100%;align-items:flex-start;cursor:text;',
    'align-content:flex-start}',
    '.tag-input:focus-within{border-color:var(--vscode-focusBorder)}',
    '.tag-input input{flex:1;min-width:80px;border:none;background:none;',
    'padding:2px 4px;font-size:12px;color:var(--vscode-input-foreground);outline:none}',
    '.tag-item{display:inline-flex;align-items:center;padding:2px 8px;border-radius:3px;',
    'font-size:11px;background:var(--vscode-badge-background);',
    'color:var(--vscode-badge-foreground);cursor:pointer;user-select:none}',
    ".tag-item::after{content:'\\00d7';margin-left:3px;opacity:.7}",
    '.tag-item:hover{opacity:.7}',
].join('') + [
    '.btn-danger{background:rgba(239,68,68,.15);color:#EF4444}',
    '.btn-danger:hover{background:rgba(239,68,68,.25)}',
    '.server-form{background:rgba(255,255,255,.03);border-radius:8px;padding:20px;',
    'border:1px solid var(--vscode-input-border,rgba(255,255,255,.08))}',
    '.sf-row{margin-bottom:14px}',
    '.sf-label{display:block;font-size:12px;font-weight:500;margin-bottom:4px;',
    'color:var(--vscode-foreground)}',
    '.sf-input{width:100%;background:var(--vscode-input-background);',
    'color:var(--vscode-input-foreground);',
    'border:1px solid var(--vscode-input-border,transparent);',
    'padding:6px 10px;border-radius:4px;font-size:13px;',
    'font-family:var(--vscode-font-family);outline:none}',
    '.sf-input:focus{border-color:var(--vscode-focusBorder)}',
    '.sf-row .input-row{display:flex;gap:6px}',
    '.sf-row .input-row .sf-input{flex:1;min-width:0}',
    '.sf-actions{margin-top:18px;display:flex;gap:8px;padding-top:14px;',
    'border-top:1px solid rgba(255,255,255,.06)}',
    '.env-expand{max-height:0;overflow:hidden;transition:max-height .25s ease,padding .25s ease;',
    'padding:0 0;margin-top:0}',
    '.env-expand.open{max-height:500px;overflow:visible;padding:14px 0 0;margin-top:12px;',
    'border-top:1px solid rgba(255,255,255,.06)}',
    '.env-toggle-btn{display:inline-flex;align-items:center;gap:4px}',
    '.env-toggle-arrow{display:inline-block;font-size:10px;transition:transform .2s}',
    '.env-toggle-btn.active{background:var(--vscode-button-background);',
    'color:var(--vscode-button-foreground)}',
    '.ef-row{margin-bottom:12px}',
    '.ef-label{display:block;font-size:12px;font-weight:500;margin-bottom:4px;',
    'color:var(--vscode-foreground)}',
    '.ef-opt{font-weight:400;color:var(--vscode-descriptionForeground);margin-left:6px}',
    '.ef-input{width:100%;background:var(--vscode-input-background);',
    'color:var(--vscode-input-foreground);',
    'border:1px solid var(--vscode-input-border,transparent);',
    'padding:6px 10px;border-radius:4px;font-size:13px;',
    'font-family:var(--vscode-font-family);outline:none}',
    '.ef-input:focus{border-color:var(--vscode-focusBorder)}',
    '.ef-row .input-row{display:flex;gap:6px}',
    '.ef-row .input-row .ef-input{flex:1;min-width:0}',
].join('') + [
    '.csel{position:relative;width:100%;text-align:left}',
    '.csel-trigger{display:flex;align-items:center;justify-content:space-between;',
    'width:100%;background:var(--vscode-input-background);',
    'color:var(--vscode-input-foreground);',
    'border:1px solid var(--vscode-input-border,transparent);',
    'padding:6px 10px;border-radius:4px;font-size:13px;',
    'font-family:var(--vscode-font-family);cursor:pointer;user-select:none}',
    '.csel-trigger:hover{border-color:var(--vscode-focusBorder)}',
    '.csel.disabled .csel-trigger{opacity:.65;cursor:wait;pointer-events:none}',
    ".csel-trigger::after{content:'\\25BE';font-size:10px;opacity:.6;margin-left:8px}",
    '.csel.open .csel-trigger{border-color:var(--vscode-focusBorder)}',
    ".csel.open .csel-trigger::after{content:'\\25B4'}",
    '.csel-list{position:absolute;top:calc(100% + 2px);left:0;right:0;',
    'background:var(--vscode-dropdown-background,var(--vscode-input-background));',
    'border:1px solid var(--vscode-dropdown-border,var(--vscode-input-border,rgba(255,255,255,.1)));',
    'border-radius:4px;max-height:180px;overflow-y:auto;z-index:100;',
    'display:none;box-shadow:0 4px 12px rgba(0,0,0,.3)}',
    '.csel.open .csel-list{display:block}',
    '.csel-item{padding:6px 10px;font-size:13px;cursor:pointer;',
    'color:var(--vscode-dropdown-foreground,var(--vscode-input-foreground))}',
    '.csel-item:hover{background:var(--vscode-list-hoverBackground,rgba(255,255,255,.06))}',
    '.csel-item.active{background:var(--vscode-list-activeSelectionBackground,rgba(0,122,204,.3));',
    'color:var(--vscode-list-activeSelectionForeground,var(--vscode-foreground))}',
].join('') + [
    '.section-collapse{margin-bottom:8px;border:1px solid var(--vscode-panel-border,rgba(255,255,255,.06));',
    'border-radius:6px;padding:0}',
    '.section-collapse[open]{padding-bottom:12px}',
    '.section-header{font-size:14px;font-weight:600;cursor:pointer;padding:10px 12px;',
    'user-select:none;list-style:none;display:flex;align-items:center;gap:8px}',
    '.section-header::-webkit-details-marker{display:none}',
    ".section-header::before{content:'\\25B6';font-size:10px;opacity:.6;transition:transform .2s}",
    "details.section-collapse[open]>.section-header::before{transform:rotate(90deg)}",
    '.section-collapse>:not(summary){padding:0 12px}',
    '.section-badge{font-size:11px;font-weight:400;padding:2px 8px;border-radius:3px;',
    'color:var(--vscode-descriptionForeground);',
    'background:var(--vscode-badge-background,rgba(255,255,255,.08))}',
    '.section-inactive{padding:4px 0 8px}',
    '.section-inactive-hint{font-size:12px;color:var(--vscode-descriptionForeground);margin-bottom:8px}',
].join('');
