/**
 * CLI UI text dictionary shard — shared labels, status/remote/deploy/sync/build short texts.
 * Split from types.ts (entries copied verbatim; do not edit wording).
 */
export const UI_COMMON: Record<string, { en: string; zh: string }> = {
    // common
    error:                         { en: 'Error',                        zh: '错误' },
    warning:                       { en: 'Warning',                      zh: '警告' },
    info:                          { en: 'Info',                         zh: '信息' },
    hint:                          { en: 'hint',                        zh: '提示' },
    saved:                         { en: 'Saved',                       zh: '已保存' },
    detected:                      { en: 'Detected',                    zh: '检测到' },
    activeTarget:                  { en: 'Active target',               zh: '活动目标' },
    language:                      { en: 'Language',                    zh: '语言' },
    next:                          { en: 'Next',                        zh: '后续' },
    workspace:                     { en: 'Workspace',                   zh: '工作区' },
    changed:                       { en: 'Changed',                     zh: '已变更' },
    none:                          { en: '(none)',                       zh: '（无）' },
    noneFound:                     { en: '(none found)',                 zh: '（未找到）' },
    nothingDetected:               { en: '(nothing detected)',           zh: '（未检测到）' },
    notConfigured:                 { en: 'not configured',               zh: '未配置' },
    configured:                    { en: 'configured',                   zh: '已配置' },
    available:                     { en: 'available',                    zh: '可用' },
    cleared:                       { en: 'cleared',                      zh: '已清除' },
    // status
    readiness:                     { en: 'Readiness',                   zh: '就绪度' },
    toolchainLabel:                { en: 'Toolchain',                   zh: '工具链' },
    remoteLabel:                   { en: 'Remote',                      zh: '远程' },
    syncLabel:                     { en: 'Sync',                        zh: '同步' },
    runtimeLabel:                  { en: 'Runtime',                     zh: '运行时' },
    running:                       { en: 'running',                      zh: '运行中' },
    notRunning:                    { en: 'not running',                  zh: '未运行' },
    enabledStatus:                 { en: 'enabled',                      zh: '已启用' },
    disabledStatus:                { en: 'disabled',                     zh: '未启用' },
    executable:                    { en: 'executable',                  zh: '可执行文件' },
    log:                           { en: 'log',                         zh: '日志' },
    pid:                           { en: 'pid',                          zh: '进程' },
    // readiness keys
    readinessTarget:               { en: 'target',                       zh: '目标' },
    readinessToolchain:            { en: 'toolchain',                    zh: '工具链' },
    readinessSync:                 { en: 'sync',                         zh: '同步' },
    readinessRemote:               { en: 'remote',                       zh: '远程' },
    readinessRuntime:              { en: 'runtime',                      zh: '运行时' },
    // target detail labels
    projectLabel:                  { en: 'Project',                     zh: '项目' },
    modeLabel:                     { en: 'Mode',                        zh: '模式' },
    archLabel:                     { en: 'Arch',                        zh: '架构' },
    kind:                          { en: 'Kind',                        zh: '类型' },
    // status diagnostics
    noActiveTarget:                { en: 'No active target selected',    zh: '未选择活动目标' },
    notInitialized:                { en: 'Not initialized, no config found', zh: '未初始化，未找到配置' },
    statusSetupLocal:              { en: 'local setup',                     zh: '本地初始化' },
    statusSetupRemote:             { en: 'local + remote setup',            zh: '本地 + 远程初始化' },
    noSyncServer:                  { en: 'No sync server added',         zh: '未添加同步服务器' },
    remotePathNotConfigured:       { en: 'Remote path not configured',   zh: '远程路径未配置' },
    remoteNoServerConfigured:      { en: 'No remote server configured',  zh: '未配置远程服务器' },
    remoteModeOn:                  { en: 'Remote mode enabled',           zh: '远程模式已开启' },
    remoteModeAlreadyOn:           { en: 'Remote mode is already enabled', zh: '远程模式已经是开启状态' },
    remoteModeOff:                 { en: 'Remote mode disabled',          zh: '远程模式已关闭' },
    remoteModeAlreadyOff:          { en: 'Remote mode is already disabled', zh: '远程模式已经是关闭状态' },
    remoteModeLabel:               { en: 'Mode',                          zh: '模式' },
    remoteModeLocal:               { en: 'local',                         zh: '本地' },
    remoteModeRemote:              { en: 'remote',                        zh: '远程' },
    remoteCheckLabel:              { en: 'Code consistency check',         zh: '代码一致性检查' },
    remoteCheckBranch:             { en: 'Branch',                        zh: '分支' },
    remoteCheckCommit:             { en: 'Commit',                        zh: '提交' },
    remoteCheckRemote:             { en: 'remote',                        zh: '远程' },
    remoteCheckNeedsRemoteMode:  { en: 'Remote mode is not enabled',        zh: '远程模式未开启' },
    remoteCheckDirty:              { en: '(dirty)',                             zh: '(有改动)' },
    remoteCheckNoRemote:           { en: 'remote not found',                   zh: '远程不存在' },
    remoteCheckMatched:            { en: 'matched',                            zh: '一致' },
    remoteCheckCommitMismatch:     { en: 'commit mismatch',                    zh: '提交不一致' },
    remoteCheckNoRemoteSummary:    { en: 'remote not found',                   zh: '远程不存在' },
    remoteCheckLocalMissing:      { en: 'local not found',                    zh: '本地不存在' },
    remoteCheckLocalMissingSummary: { en: 'local not found',                  zh: '本地不存在' },
    remoteCheckRelation_ahead:    { en: 'remote behind',                     zh: '远程落后' },
    remoteCheckRelation_behind:   { en: 'remote ahead',                      zh: '远程超前' },
    remoteCheckRelation_diverged: { en: 'diverged',                          zh: '远程分叉' },
    'remote.noServers':            { en: 'No servers configured',            zh: '没有可用的服务器' },
    'remote.selectServer':         { en: 'Please select a server',           zh: '请选择服务器' },
    'remote.chooseServer':         { en: 'Select target server:',            zh: '选择目标服务器:' },
    deployNoArtifacts:              { en: 'No artifacts specified. Use --artifact or configure with forja deploy config', zh: '未指定产物。用 --artifact 或 forja deploy config 配置' },
    deployDownloadDone:             { en: 'Downloaded {0} artifact(s)',       zh: '已下载 {0} 个产物' },
    deployConfigSaved:              { en: 'Deploy configuration saved',       zh: '部署配置已保存' },
    deployNotConfigured:            { en: 'Deploy target not configured',     zh: '部署目标未配置' },
    deployBuilding:                 { en: 'Building on remote...',            zh: '远程构建中...' },
    deployBuildDone:                { en: '✓ Build complete',                 zh: '✓ 构建完成' },
    deployBuildFailed:              { en: 'Remote build failed',              zh: '远程构建失败' },
    deployDownloading:              { en: 'Downloading',                      zh: '下载中' },
    deployDownloadFailed:           { en: 'Failed to download artifacts',     zh: '下载产物失败' },
    deploySshFailed:                { en: 'SSH to target failed, falling back to HTTP', zh: 'SSH 连接实体机失败，降级到 HTTP' },
    deployUploadFailed:             { en: 'Failed to upload artifact',        zh: '上传产物失败' },
    deployDone:                     { en: '✓ Deploy complete',                zh: '✓ 部署完成' },
    deployFallback:                 { en: 'Starting fallback HTTP server...', zh: '启动备用 HTTP 服务...' },
    deployFallbackHint:             { en: 'Download from target machine browser:', zh: '在实体机浏览器中下载:' },
    deployFallbackPressEnter:       { en: 'Press Enter after download to stop', zh: '下载完成后按 Enter 停止服务' },
    deployFallbackUrl:              { en: 'Fallback URL',                     zh: '备用下载地址' },
    deployFallbackFailed:           { en: 'Failed to start HTTP server on build server', zh: '编译服务器上启动 HTTP 服务失败' },
    'deploy.targetNotFound':        { en: 'Deploy target server not found',   zh: '部署目标服务器未找到' },
    remoteForjaBinDefault:         { en: 'Remote Forja bin not configured, will use npm global prefix', zh: '远程 Forja 二进制未配置，将使用 npm 全局 prefix' },
    qtNotFound:                    { en: 'Qt not found at configured path', zh: '在配置路径未找到 Qt' },
    vsNotFound:                    { en: 'VS dev environment not found', zh: '未找到 VS 开发环境' },
    vsNotFoundDetail:              { en: 'VS dev environment not found (vsDevShell)', zh: '未找到 VS 开发环境（vsDevShell）' },
    jomNotFound:                   { en: 'jom not found (optional, recommended for faster builds)', zh: '未找到 jom（可选，建议安装以加速构建）' },
    makeNotFound:                  { en: 'make not found',              zh: '未找到 make' },
    // hints
    fileMayDeleted:                { en: 'The file may have been deleted or moved', zh: '文件可能已被删除或移动' },
    serverDeleted:                 { en: 'Server was deleted, please re-select', zh: '服务器已被删除，请重新选择' },
    qtReconfigure:                 { en: 'Qt installation may have changed, reconfigure with forja use', zh: 'Qt 安装可能已变更，请用 forja use 重新配置' },
    installVs:                     { en: 'Install Visual Studio and configure vcvarsall.bat', zh: '安装 Visual Studio 并配置 vcvarsall.bat' },
    installVsCpp:                  { en: 'Install Visual Studio and configure with forja use target --vs', zh: '安装 Visual Studio 并用 forja use target --vs 配置' },
    installBuildEssential:         { en: 'Install build-essential or equivalent', zh: '安装 build-essential 或同等工具' },
    deployRemote:                  { en: 'Run forja remote bootstrap to deploy the current CLI', zh: '运行 forja remote bootstrap 部署当前 CLI' },
    // list
    targets:                       { en: 'Targets',                      zh: '目标' },
    servers:                       { en: 'Servers',                      zh: '服务器' },
    environment:                   { en: 'Environment',                  zh: '环境' },
    remoteConfiguration:           { en: 'Remote Configuration',         zh: '远程配置' },
    workspaceMode:                 { en: 'Workspace mode',              zh: '工作区模式' },
    remoteWorkspace:               { en: 'Remote workspace',            zh: '远程工作区' },
    forjaBin:                      { en: 'Forja bin',                   zh: 'Forja 二进制' },
    buildOrder:                    { en: 'Build order',                 zh: '构建顺序' },
    transfer:                      { en: 'Transfer',                    zh: '传输' },
    repos:                         { en: 'Repos',                       zh: '仓库' },
    project:                       { en: 'project',                     zh: '项目' },
    mode:                          { en: 'mode',                        zh: '模式' },
    arch:                          { en: 'arch',                       zh: '架构' },
    enabled:                       { en: 'enabled=',                     zh: '已启用=' },
    server:                        { en: 'server=',                      zh: '服务器=' },
    path:                          { en: 'path',                        zh: '路径' },
    baseline:                      { en: 'baseline',                    zh: '基线' },
    artifacts:                     { en: 'artifacts',                   zh: '制品' },
    strictHostKey:                 { en: 'StrictHostKey',               zh: '严格主机密钥' },
    // use
    updated:                       { en: 'updated',                      zh: '已更新' },
    target:                        { en: 'Target',                      zh: '目标' },
    profile:                       { en: 'Profile',                     zh: '配置方案' },
    // server
    serverAdded:                   { en: 'Server added',                 zh: '服务器已添加' },
    serverUpdated:                 { en: 'Server updated',               zh: '服务器已更新' },
    serverRemoved:                 { en: 'Server removed',               zh: '服务器已移除' },
    id:                            { en: 'ID',                          zh: 'ID' },
    name:                          { en: 'Name',                        zh: '名称' },
    host:                          { en: 'Host',                        zh: '主机' },
    port:                          { en: 'Port',                        zh: '端口' },
    username:                      { en: 'Username',                    zh: '用户名' },
    auth:                          { en: 'Auth',                        zh: '认证' },
    key:                           { en: 'Key',                         zh: '密钥' },
    planDryRun:                    { en: 'Plan (dry run)',              zh: '计划（预演）' },
    wouldWrite:                    { en: 'Would write',                 zh: '将写入' },
    wouldRun:                      { en: 'Would run',                   zh: '将运行' },
    commands:                      { en: 'Commands',                    zh: '命令' },
    // sync
    syncPlan:                      { en: 'Sync plan (dry run)',          zh: '同步计划（预演）' },
    'sync.notConfigured':          { en: 'No sync server configured',   zh: '未配置同步服务器' },
    'syncInteractiveSetup':        { en: 'Interactive sync setup',       zh: '交互式同步配置' },
    'sync.serverNotFound':         { en: 'Server not found',            zh: '服务器未找到' },
    'sync.planFailed':             { en: 'Plan failed',                 zh: '计划失败' },
    'sync.syncFailed':             { en: 'Sync failed',                 zh: '同步失败' },
    'sync.remoteBlocked':          { en: 'Sync failed',                 zh: '同步失败' },
    'sync.unknownFlag':            { en: 'Unknown flag(s)',             zh: '未知参数' },
    'sync.unknownAction':          { en: 'Unknown sync action',         zh: '未知同步动作' },
    'sync.noRemotePath':           { en: 'Remote path not configured',  zh: '未配置远程路径' },
    'sync.noGitRepos':             { en: 'No git repositories found',   zh: '未找到 git 仓库' },
    'sync.filesNotFound':          { en: 'Specified files not found in any git root', zh: '指定文件在任何 git 仓库中均未找到' },
    'sync.passwordRequired':       { en: 'Password not provided. Set FORJA_SSH_PASSWORD or enter interactively', zh: '未提供密码。可通过环境变量 FORJA_SSH_PASSWORD 设置，或在 TTY 中交互输入' },
    'sync.passwordPrompt':         { en: 'Password for',                    zh: '输入' },
    'sync.ambiguous':              { en: 'matched multiple servers, use id', zh: '匹配到多个服务器，请使用 id' },
    'sync.createRemoteDirFailed':  { en: 'Create remote directory failed', zh: '创建远程目录失败' },
    'sync.resetDone':              { en: 'Sync state cleared; next sync will recalculate', zh: '已清除同步状态；下次同步会重新计算待同步文件' },
    syncConfirm:                   { en: 'Proceed with sync?',          zh: '确认执行同步？' },
    syncResetConfirm:              { en: 'Sync reset: clear all sync state. Continue?', zh: '同步重置：清除所有同步状态。继续？' },
    'sync.dryRunIncompatible':      { en: '--dry-run cannot be used with this subcommand', zh: '--dry-run 不能与此子命令一起使用' },
    'sync.fileOnlyForExecute':      { en: '--file can only be used with sync execute/plan', zh: '--file 只能在 sync 执行/计划时使用' },
    'sync.dryRunYesConflict':       { en: '--dry-run and --yes cannot be used together', zh: '--dry-run 和 --yes 不能同时使用' },
    'sync.ignoreFlagsOnlyWithIgnore': { en: '--add/--rm can only be used with sync ignore', zh: '--add/--rm 仅适用于 sync ignore' },
    syncIgnoreAddRmConflict:      { en: 'Cannot use --add and --rm together', zh: '不能同时使用 --add 和 --rm' },
    syncCancelled:                 { en: 'Sync cancelled',              zh: '同步已取消' },
    syncNothing:                   { en: 'Nothing to sync',             zh: '没有需要同步的内容' },
    syncComplete:                  { en: 'Sync complete',                zh: '同步完成' },
    syncStateReset:                { en: 'Sync state reset',             zh: '同步状态已重置' },
    syncIgnore:                    { en: 'Ignore',                        zh: '忽略' },
    syncIgnoreEmpty:               { en: 'No ignore patterns configured', zh: '未配置忽略规则' },
    syncIgnoreAdded:               { en: 'Added: {0}',                    zh: '已添加：{0}' },
    syncIgnoreRemoved:             { en: 'Removed: {0}',                  zh: '已移除：{0}' },
    syncIgnoreAlreadyExists:       { en: 'Already in ignore list: {0}',   zh: '已在忽略列表中：{0}' },
    syncIgnoreNotFound:            { en: 'Not in ignore list: {0}',       zh: '不在忽略列表中：{0}' },
    syncIgnorePatternRequired:     { en: 'Pattern required. Usage: forja sync ignore --add <pattern>', zh: '需要提供规则。用法：forja sync ignore --add <pattern>' },
    pending:                       { en: 'Pending',                      zh: '待同步' },
    uploaded:                      { en: 'Uploaded',                     zh: '已上传' },
    deleted:                       { en: 'Deleted',                      zh: '已删除' },
    skipped:                       { en: 'Skipped',                      zh: '已跳过' },
    // build/run/clean/stop
    build:                         { en: 'Build',                        zh: '构建' },
    buildSucceeded:                { en: 'succeeded',                    zh: '成功' },
    buildFailed:                   { en: 'failed',                       zh: '失败' },
    duration:                      { en: 'Duration',                    zh: '耗时' },
    errors:                        { en: 'Errors',                      zh: '错误' },
    warnings:                      { en: 'Warnings',                    zh: '警告' },
    run:                           { en: 'Run',                          zh: '运行' },
    runCompleted:                  { en: 'completed',                    zh: '已完成' },
    runFailed:                     { en: 'failed',                       zh: '失败' },
    pidLabel:                      { en: 'PID',                          zh: '进程ID' },
    clean:                         { en: 'Clean',                        zh: '清理' },
    cleanSucceeded:                { en: 'succeeded',                    zh: '成功' },
    cleanFailed:                   { en: 'failed',                       zh: '失败' },
    cleaned:                       { en: 'Cleaned',                     zh: '已清理' },
    state:                         { en: 'State',                       zh: '状态' },
    processStopped:                { en: 'Process stopped',              zh: '进程已停止' },
    noRunningProcess:              { en: 'No running process',           zh: '没有运行中的进程' },
    stopNotSupported:              { en: 'Stop not supported for this target', zh: '此目标不支持停止' },
    stopCppUnsupported:            { en: 'C++ target does not support stop. C++ builds are not long-running.', zh: 'C++ 目标不支持停止。C++ 构建不是长运行进程。' },
    stopTerminateFailed:           { en: 'Failed to terminate process',  zh: '终止进程失败' },
    stopStillRunning:              { en: 'Process still running',        zh: '进程仍在运行' },
    // list extras
    configuredMark:                { en: '[configured]',                 zh: '[已配置]' },
    serverIdLabel:                 { en: 'ID',                          zh: 'ID' },
    serverNameLabel:               { en: 'Name',                        zh: '名称' },
    serverHostLabel:               { en: 'Host',                        zh: '主机' },
    serverPortLabel:               { en: 'Port',                        zh: '端口' },
    serverUsernameLabel:           { en: 'Username',                    zh: '用户名' },
    serverAuthLabel:               { en: 'Auth',                        zh: '认证' },
    // list env labels
    qtLabel:                       { en: 'Qt',                          zh: 'Qt' },
    vsLabel:                       { en: 'VS',                          zh: 'VS' },
    jomLabel:                      { en: 'jom',                         zh: 'jom' },
    makeLabel:                     { en: 'make',                        zh: 'make' },
    roleLabel:                     { en: 'role',                        zh: '角色' },
    // setup summary labels (used by use.ts / report.ts)
    setupTitle:                    { en: 'Target Configuration',          zh: 'Forja 初始化' },
    setupSummaryQt:                { en: 'Qt',                           zh: 'Qt' },
    setupSummaryVs:                { en: 'VS',                           zh: 'VS' },
    setupSummaryModeArch:          { en: 'Mode/Arch',                    zh: '模式/架构' },
    // server selection (used by index.ts)
    setupSelectServer:             { en: 'Select a server',                zh: '选择服务器' },
    setupRemotePathPrompt:         { en: 'Remote path',                     zh: '远程路径' },
    // server creation (used by index.ts)
    setupServerCreated:            { en: 'Server created',                zh: '已创建服务器' },
    setupPromptHost:               { en: 'Host address',                  zh: '主机地址' },
    setupPromptUsername:           { en: 'Username',                      zh: '用户名' },
    setupPromptPort:               { en: 'Port',                          zh: '端口' },
    setupPromptAuthMode:           { en: 'Auth mode',                     zh: '认证方式' },
    setupAuthKey:                  { en: 'Key',                           zh: '密钥' },
    setupAuthPassword:             { en: 'Password',                      zh: '密码' },
    setupPromptPrivateKey:         { en: 'Private key path',              zh: '私钥路径' },
    setupPromptPassword:           { en: 'Password',                      zh: '密码' },
    setupPromptName:               { en: 'Server name',                   zh: '服务器名称' },
    // answers / questions (used by useTarget)
    setupAnswersLoadFailed:        { en: 'Failed to load answers file', zh: '加载答案文件失败' },
    setupQuestionTarget:           { en: 'Select target',                 zh: '选择目标' },
    setupQuestionQtPath:           { en: 'Qt path',                       zh: 'Qt 路径' },
    setupQuestionVsInstall:        { en: 'VS install',                    zh: 'VS 安装' },
    setupQuestionMode:             { en: 'Build mode',                    zh: '构建模式' },
    setupQuestionArch:             { en: 'Target arch',                   zh: '目标架构' },
    // sync extras
    serverLabel:                   { en: 'Server',                      zh: '服务器' },
    remotePathLabel:               { en: 'Remote path',                 zh: '远程路径' },
};
