/**
 * Auto-increment patch version in package.json.
 * Usage: node scripts/bump-version.js
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const file = path.join(root, 'package.json');

const pkg = JSON.parse(fs.readFileSync(file, 'utf-8'));
const parts = pkg.version.split('.');
parts[2] = String(Number(parts[2]) + 1);
pkg.version = parts.join('.');
fs.writeFileSync(file, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
console.log(`${path.basename(file)} → ${pkg.version}`);

// Sync version to src/version.ts
const versionFile = path.join(root, 'src', 'version.ts');
const versionContent = `/** Auto-generated by scripts/bump-version.js — do not edit manually. */\nexport const VERSION = '${pkg.version}';\n`;
fs.writeFileSync(versionFile, versionContent, 'utf-8');
console.log(`src/version.ts → ${pkg.version}`);
