/**
 * Sync src/version.ts from package.json version.
 * Runs automatically before every compile to prevent drift.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
const versionFile = path.join(root, 'src', 'version.ts');
const expected = `/** Auto-generated by scripts/bump-version.js — do not edit manually. */\nexport const VERSION = '${pkg.version}';\n`;

const current = fs.existsSync(versionFile) ? fs.readFileSync(versionFile, 'utf-8') : '';
if (current !== expected) {
    fs.writeFileSync(versionFile, expected, 'utf-8');
    console.log(`src/version.ts → ${pkg.version}`);
}
