/**
 * ActiveTarget read/write — thin wrapper over workspaceStore.
 * Returns TargetProfile directly (no adapter layer).
 */
import { resolveWorkroot, loadWorkspaceConfig, saveWorkspaceConfig, getActiveTarget as getTargetProfile } from '../../core/workspaceStore';
import type { TargetProfile } from '../../core/workspaceStore';
import { T } from './types';

/** Resolve workroot from cwd and return the active target, or null. */
export function getActiveTarget(cwd: string): TargetProfile | null {
    const workroot = resolveWorkroot(cwd);
    if (!workroot) { return null; }
    const config = loadWorkspaceConfig(workroot);
    return getTargetProfile(config);
}

/** Returns true if save succeeded, false if workroot not registered or no active target. */
export function setActiveTarget(cwd: string, target: TargetProfile): boolean {
    const workroot = resolveWorkroot(cwd);
    if (!workroot) { return false; }
    const config = loadWorkspaceConfig(workroot);
    if (!config.activeTarget) { return false; }
    if (!config.targets[config.activeTarget]) { return false; }

    // Replace the active target profile entirely
    config.targets[config.activeTarget] = target;
    try {
        saveWorkspaceConfig(config);
    } catch {
        return false;
    }
    return true;
}

export function requireActiveTarget(cwd: string): { target: TargetProfile } | { error: string; nextAction?: string } {
    const target = getActiveTarget(cwd);
    if (!target) {
        const workroot = resolveWorkroot(cwd);
        return {
            error: T('cmd.noActiveTarget'),
            nextAction: workroot ? 'forja use target' : 'forja init',
        };
    }
    return { target };
}

/** Strip --json from nextAction strings generated by core plan helpers. */
export function stripJsonFlag(s: string | undefined): string | undefined {
    return s?.replace(/\s+--json/g, '');
}
