/**
 * ActiveTarget read/write — reads from workspaceStore, returns legacy ActiveTarget shape.
 */
import { resolveWorkroot, loadWorkspaceConfig, saveWorkspaceConfig, getActiveTarget as getTargetProfile } from '../../core/workspaceStore';
import type { TargetProfile } from '../../core/workspaceStore';
import { ActiveTarget, T } from './types';

/** Convert TargetProfile to legacy ActiveTarget shape for downstream compatibility. */
export function targetProfileToActiveTarget(profile: TargetProfile, workroot: string): ActiveTarget {
    return {
        kind: profile.kind,
        project: profile.project,
        mode: profile.mode,
        arch: profile.arch,
        runAt: profile.runAt,
        qtPath: profile.toolchain.qtPath,
        vsInstall: profile.toolchain.vsInstall,
        jomPath: profile.toolchain.jomPath,
        qmakeTarget: profile.toolchain.qmakeTarget,
        qtVersion: profile.toolchain.qtVersion,
    };
}

/** Resolve workroot from cwd and return the active target, or null. */
export function getActiveTarget(cwd: string): ActiveTarget | null {
    const workroot = resolveWorkroot(cwd);
    if (!workroot) { return null; }
    const config = loadWorkspaceConfig(workroot);
    const profile = getTargetProfile(config);
    if (!profile) { return null; }
    return targetProfileToActiveTarget(profile, workroot);
}

export function setActiveTarget(cwd: string, target: ActiveTarget): void {
    const workroot = resolveWorkroot(cwd);
    if (!workroot) { return; }
    const config = loadWorkspaceConfig(workroot);
    if (!config.activeTarget) { return; }
    const profile = config.targets[config.activeTarget];
    if (!profile) { return; }

    // Update profile fields from ActiveTarget
    profile.mode = target.mode;
    profile.arch = target.arch;
    profile.runAt = target.runAt;
    if (target.qtPath !== undefined) profile.toolchain.qtPath = target.qtPath;
    if (target.vsInstall !== undefined) profile.toolchain.vsInstall = target.vsInstall;
    if (target.jomPath !== undefined) profile.toolchain.jomPath = target.jomPath;
    if (target.qmakeTarget !== undefined) profile.toolchain.qmakeTarget = target.qmakeTarget;

    saveWorkspaceConfig(config);
}

export function requireActiveTarget(cwd: string): { target: ActiveTarget } | { error: string; nextAction?: string } {
    const target = getActiveTarget(cwd);
    if (!target) {
        const workroot = resolveWorkroot(cwd);
        return {
            error: T('cmd.noActiveTarget'),
            nextAction: workroot ? 'forja use target' : 'forja init',
        };
    }
    return { target };
}

/** No longer needed — workspaceStore is the single source of truth. Returns input unchanged. */
export function tryPinnedProjectFallback(
    _workspace: string,
    targetResult: { target: ActiveTarget } | { error: string; nextAction?: string },
): { target: ActiveTarget } | { error: string; nextAction?: string } {
    return targetResult;
}

/** Strip --json from nextAction strings generated by core plan helpers. */
export function stripJsonFlag(s: string | undefined): string | undefined {
    return s?.replace(/\s+--json/g, '');
}
