/**
 * ActiveTarget read/write — thin wrapper over settingsIO for CLI.
 */
import * as path from 'path';
import * as fs from 'fs';
import { loadActiveTarget, saveActiveTarget, loadSdkSettings } from '../../core/settingsIO';
import { ActiveTarget, T } from './types';

export function getActiveTarget(workspace: string): ActiveTarget | null {
    const raw = loadActiveTarget(workspace);
    if (!raw) { return null; }
    return raw;
}

export function setActiveTarget(workspace: string, target: ActiveTarget): void {
    saveActiveTarget(workspace, target);
}

export function requireActiveTarget(workspace: string): { target: ActiveTarget } | { error: string; nextAction?: string } {
    const target = getActiveTarget(workspace);
    if (!target) {
        return {
            error: T('cmd.noActiveTarget'),
            nextAction: 'forja list targets',
        };
    }
    return { target };
}

/**
 * Fallback: if targetResult has error, try SDK pinnedProject to synthesize a target.
 * Returns the (possibly updated) targetResult.
 */
export function tryPinnedProjectFallback(
    workspace: string,
    targetResult: { target: ActiveTarget } | { error: string; nextAction?: string },
): { target: ActiveTarget } | { error: string; nextAction?: string } {
    if ('target' in targetResult) { return targetResult; }
    const sdkSettings = loadSdkSettings(workspace);
    if (sdkSettings.pinnedProject) {
        const projectPath = path.isAbsolute(sdkSettings.pinnedProject)
            ? sdkSettings.pinnedProject
            : path.join(workspace, sdkSettings.pinnedProject);
        if (fs.existsSync(projectPath)) {
            return {
                target: {
                    kind: 'sdk',
                    project: sdkSettings.pinnedProject,
                    mode: sdkSettings.mode || 'debug',
                    arch: sdkSettings.arch || (process.platform === 'win32' ? 'x86' : 'x64'),
                    runAt: 'local',
                },
            };
        }
    }
    return targetResult;
}

/** Strip --json from nextAction strings generated by core plan helpers. */
export function stripJsonFlag(s: string | undefined): string | undefined {
    return s?.replace(/\s+--json/g, '');
}
